"""common/pgdb/schema.py —— PostgreSQL 侧的完整 DDL。

OWNS:
    init_tables()          —— 幂等，可反复执行
    verify_schema()        —— 断言列集与列序，与 SQLite 新库逐列比对
    reset_all()            —— 测试/清库用（TRUNCATE ... RESTART IDENTITY）

--------------------------------------------------------------------------
类型决策（已定，不要推翻）
--------------------------------------------------------------------------
* 时间戳一律 ``text``，格式 ``'%Y-%m-%d %H:%M:%S'``，**不是** timestamptz。
  硬证据：server/app.py:1168 与 487 对该值做 ``datetime.strptime(x[:19], ...)``，
  datetime 对象不可下标 → TypeError；而且 asyncpg 会把 timestamptz 还成
  datetime，FastAPI 再序列化成 ISO-8601，erpAPI 拿到的每一条 created_at/
  updated_at 都变形。
  ⚠ ``DEFAULT CURRENT_TIMESTAMP`` 在 PG 的 text 列上**不会报错**，但会存成
  ``'2026-08-04 20:25:57.851686+00'``（带微秒和时区偏移）——静默变形。
  所以默认值一律写 ``to_char(clock_timestamp() AT TIME ZONE 'UTC', ...)``。
  用 clock_timestamp() 而不是 now()：SQLite 的 CURRENT_TIMESTAMP 在同一个事务里
  会往前走，now() 冻在事务开始时刻。
* 布尔一律 ``integer`` 0/1，**不是** boolean。
  ``/api/batches`` 的 needs_screenshot 在基线里是 int ``0``，而
  ``/api/tasks/pull`` 的同名字段是 ``false``（因为 database.py:1222 显式
  ``bool()`` 了一次）。同一个逻辑布尔在 API 上有两种形状，两种都被钉死了。
* id 一律 ``bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY``。
  实测：identity + ON CONFLICT DO NOTHING 与 SQLite AUTOINCREMENT + INSERT OR
  IGNORE **烧号方式完全一致**（插 a,b,c 再插 a,b,c 再插 d,e → 1,2,3,7,8）。
  基线钉死的空洞：golden_batch_b 的 id 是 3 不是 2（撞名那一发照样烧掉号 2，
  哪怕它现在回的是 409）。tasks 那边的空洞自撞名改 409 后不再由黄金覆盖
  （基线 task id 是 1,3,4,5），改由 tests/pgdb/test_tasks.py 单独看守。
  → 绝不允许"先 SELECT 再 INSERT" / "WHERE NOT EXISTS" 之类的预过滤优化。
  用 BY DEFAULT 而非 ALWAYS：ALWAYS 会挡住将来的显式 id 回填。
* 所有 text 列都带 ``COLLATE "C"``。
  SQLite 的 TEXT 比较是 BINARY（字节序）。scraper_dev 恰好是 C.UTF-8 所以现在
  看不出问题，但生产库若用 en_US.UTF-8 建，``iter_results`` 的 keyset 游标
  （``ba.asin > $n ORDER BY ba.asin``）会重排导出行序、``updated_at < cutoff``
  的回收判定也会漂。逐列 COLLATE "C" 能扛住"恢复到另一台 collation 不同的库"。

--------------------------------------------------------------------------
不移植的东西
--------------------------------------------------------------------------
* 13 条 PRAGMA、WAL、只读连接池 —— 见 pool.py / admin.py。
* database.py:609-717 的 27 条 ``ALTER TABLE ... except: pass`` 迁移阶梯 ——
  **不移植**。它在新库上全是死代码（列都已在 CREATE TABLE 里），而在 PG 里
  一旦落进事务，第一条失败就会让后续全部 ``InFailedSQLTransactionError``，
  再被裸 except 吞掉 → 半张表悄悄建不出来。这里直接一次性建全列。
  代价是列序必须手工对齐 SQLite 新库的物理列序（``SELECT d.*`` 无
  response_model，列集会整个泄进 erpAPI 的响应），verify_schema() 负责守住。
* FTS5 虚表 + 3 个触发器 + rebuild 探针 —— 换成 pg_trgm 的 3 个表达式 GIN 索引。
"""
from __future__ import annotations

import logging
import os
from typing import Dict, List

logger = logging.getLogger(__name__)

# 时间戳列的默认值：与 SQLite 的 CURRENT_TIMESTAMP 逐字节同格式（UTC，无小数秒）
#
# ⚠ 交叉引用 `common/core/timeutil.py`：那边的 `TS_FMT = '%Y-%m-%d %H:%M:%S'` 是
# **同一个格式的 Python 写法**，Python 写入路径（now_ts / ts_from）与本列默认值
# 落进的是同一列。**两者必须永远一致**——格式一分叉，同一张表里就混着两种形状的
# 字符串，而这些 text 列上的所有比较（updated_at < cutoff、callback_next_retry_at
# <= now）都是字典序比较，会静默选错行。
# 本行**故意保留为 SQL 方言字面量、不参数化**：它是 DDL 里的字符串，import 不了
# Python 常量；改 timeutil 那边不会连带改这里，已建库的默认值更不会被重建。
# Phase 4.3 因此不动这一行，只加这段交叉引用。
TS_DEFAULT = "to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')"

# ASCII-only 折叠函数。**不要**用 lower()/ILIKE：它们折叠全 Unicode，
# 而 SQLite 的 LIKE 与 FTS5 trigram 只折叠 ASCII（实测 'CAFÉ CREME' 不匹配
# '%café%'）。IMMUTABLE + 与 collation 无关，所以能进表达式索引。
ASCII_LOWER_FN = """
CREATE OR REPLACE FUNCTION public.ascii_lower(t text)
RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
AS $fn$
  SELECT translate($1, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')
$fn$;
"""

# ------------------------------------------------------------------
# 建表：顺序 = SQLite 新库的物理列序（CREATE TABLE 的列 + 之后 ALTER 上去的列）
# ------------------------------------------------------------------

DDL_TABLES: List[str] = [
    # ---------------- batches（18 列）----------------
    # 注意 batch_type / discover_mode 在 SQLite 里是 ALTER 加的，所以排在
    # created_at / updated_at **之后**。get_batch_by_name 是 SELECT *，
    # 整张表的列都会泄给调用方。
    f"""
    CREATE TABLE IF NOT EXISTS batches (
        id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name                   text COLLATE "C" NOT NULL UNIQUE,
        needs_screenshot       integer DEFAULT 0,
        is_auto                integer DEFAULT 0,
        expand_variants        integer DEFAULT 0,
        status                 text COLLATE "C" DEFAULT 'running',
        completed_at           text COLLATE "C",
        external_id            text COLLATE "C",
        callback_url           text COLLATE "C",
        callback_status        text COLLATE "C",
        callback_attempts      integer DEFAULT 0,
        callback_next_retry_at text COLLATE "C",
        callback_last_error    text COLLATE "C",
        callback_sent_at       text COLLATE "C",
        created_at             text COLLATE "C" DEFAULT {TS_DEFAULT},
        updated_at             text COLLATE "C" DEFAULT {TS_DEFAULT},
        batch_type             text COLLATE "C" NOT NULL DEFAULT 'asin',
        discover_mode          text COLLATE "C"
    );
    """,

    # ---------------- batch_asins（3 列）----------------
    """
    CREATE TABLE IF NOT EXISTS batch_asins (
        batch_id bigint NOT NULL,
        asin     text COLLATE "C" NOT NULL,
        is_new   integer DEFAULT 0,
        PRIMARY KEY (batch_id, asin)
    );
    """,

    # ---------------- asin_data（55 列）----------------
    # 列集与列序是 API 契约的一部分：变异测试证实"加一列"会产生 21 处基线差异。
    f"""
    CREATE TABLE IF NOT EXISTS asin_data (
        id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        asin                        text COLLATE "C" NOT NULL UNIQUE,
        title                       text COLLATE "C",
        brand                       text COLLATE "C",
        product_type                text COLLATE "C",
        manufacturer                text COLLATE "C",
        model_number                text COLLATE "C",
        part_number                 text COLLATE "C",
        country_of_origin           text COLLATE "C",
        is_customized               text COLLATE "C",
        best_sellers_rank           text COLLATE "C",
        original_price              text COLLATE "C",
        current_price               text COLLATE "C",
        buybox_price                text COLLATE "C",
        buybox_shipping             text COLLATE "C",
        is_fba                      text COLLATE "C",
        stock_count                 text COLLATE "C",
        stock_status                text COLLATE "C",
        delivery_date               text COLLATE "C",
        delivery_time               text COLLATE "C",
        image_urls                  text COLLATE "C",
        bullet_points               text COLLATE "C",
        long_description            text COLLATE "C",
        upc_list                    text COLLATE "C",
        ean_list                    text COLLATE "C",
        parent_asin                 text COLLATE "C",
        variation_asins             text COLLATE "C",
        variant_attributes          text COLLATE "C",
        root_category_id            text COLLATE "C",
        category_ids                text COLLATE "C",
        category_tree               text COLLATE "C",
        first_available_date        text COLLATE "C",
        package_dimensions          text COLLATE "C",
        package_weight              text COLLATE "C",
        item_dimensions             text COLLATE "C",
        item_weight                 text COLLATE "C",
        product_url                 text COLLATE "C",
        site                        text COLLATE "C" DEFAULT 'amazon.com',
        zip_code                    text COLLATE "C" DEFAULT '10001',
        crawl_time                  text COLLATE "C",
        screenshot_path             text COLLATE "C",
        content_hash                text COLLATE "C",
        title_bullets_hash          text COLLATE "C",
        baseline_price              text COLLATE "C",
        baseline_buybox_price       text COLLATE "C",
        baseline_stock_count        text COLLATE "C",
        baseline_stock_status       text COLLATE "C",
        baseline_title_bullets_hash text COLLATE "C",
        baseline_updated_at         text COLLATE "C",
        rating                      text COLLATE "C",
        review_count                text COLLATE "C",
        seller_id                   text COLLATE "C",
        seller_name                 text COLLATE "C",
        created_at                  text COLLATE "C" DEFAULT {TS_DEFAULT},
        updated_at                  text COLLATE "C" DEFAULT {TS_DEFAULT},
        -- 2026-08：副标题（Title Differentiators）。
        -- ⚠ 必须是**最后一列**。老库走 init_tables 里那条
        -- `ALTER TABLE ... ADD COLUMN IF NOT EXISTS`，PG 的 ADD COLUMN 同样
        -- 只追加到末尾；插在别处会让新建库与升级库的列序分叉，而
        -- verify_schema 只能对上其中一种。
        subtitle                    text COLLATE "C"
    );
    """,

    # ---------------- asin_changes（8 列）----------------
    f"""
    CREATE TABLE IF NOT EXISTS asin_changes (
        id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        asin          text COLLATE "C" NOT NULL,
        batch_id      bigint,
        change_type   text COLLATE "C" NOT NULL,
        change_detail text COLLATE "C",
        prev_value    text COLLATE "C",
        new_value     text COLLATE "C",
        created_at    text COLLATE "C" DEFAULT {TS_DEFAULT}
    );
    """,

    # ---------------- tasks（17 列）----------------
    f"""
    CREATE TABLE IF NOT EXISTS tasks (
        id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        batch_id         bigint NOT NULL,
        asin             text COLLATE "C" NOT NULL,
        zip_code         text COLLATE "C" DEFAULT '10001',
        status           text COLLATE "C" DEFAULT 'pending',
        priority         integer DEFAULT 0,
        needs_screenshot integer DEFAULT 0,
        worker_id        text COLLATE "C",
        lease_epoch      integer DEFAULT 0,
        retry_count      integer DEFAULT 0,
        auto_retry_count integer DEFAULT 0,
        error_type       text COLLATE "C",
        error_detail     text COLLATE "C",
        created_at       text COLLATE "C" DEFAULT {TS_DEFAULT},
        updated_at       text COLLATE "C" DEFAULT {TS_DEFAULT},
        task_type        text COLLATE "C" NOT NULL DEFAULT 'asin',
        task_meta        text COLLATE "C",
        UNIQUE (batch_id, asin)
    );
    """,

    # ---------------- screenshots（9 列）----------------
    f"""
    CREATE TABLE IF NOT EXISTS screenshots (
        id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        asin         text COLLATE "C" NOT NULL,
        batch_id     bigint NOT NULL,
        status       text COLLATE "C" DEFAULT 'pending',
        retry_count  integer DEFAULT 0,
        error_detail text COLLATE "C",
        file_path    text COLLATE "C",
        created_at   text COLLATE "C" DEFAULT {TS_DEFAULT},
        updated_at   text COLLATE "C" DEFAULT {TS_DEFAULT},
        UNIQUE (batch_id, asin)
    );
    """,

    # ---------------- seller_discoveries（7 列）----------------
    f"""
    CREATE TABLE IF NOT EXISTS seller_discoveries (
        batch_id      bigint NOT NULL,
        seller_id     text COLLATE "C" NOT NULL,
        asin          text COLLATE "C" NOT NULL,
        list_title    text COLLATE "C",
        list_price    text COLLATE "C",
        list_image    text COLLATE "C",
        discovered_at text COLLATE "C" DEFAULT {TS_DEFAULT},
        PRIMARY KEY (batch_id, seller_id, asin)
    );
    """,

    # ---------------- search_discoveries（10 列，F-010）----------------
    # 关键词搜索发现结果。与 seller_discoveries 同构，多三列：
    #   page_no / rank  —— 该 ASIN 在搜索结果里的位置。这是关键词采集**独有**
    #                      的价值（排名），seller 店内列表没有对应语义。
    #   is_sponsored    —— 广告位。不记下来的话「第 3 名」这个数字毫无意义。
    #
    # ⚠ `rank` 是**页内绝对位置（1 起，含广告位）**，不是"自然排名"。
    #   两者的差别在丢弃广告位（include_sponsored=false，默认）时会现形：
    #   那时广告位那几行根本不入库，rank 序列会出现空档（1,3,4,…）——
    #   空档是**有意义的信息**（"这个位置被广告占了"），不是 bug。
    #   要自然排名就按 rank 排序后重新编号；要还原页面原貌就看空档。
    #   跨页的绝对名次推不出来：Amazon 每页条数随布局变（16/24/48/60 都见过），
    #   所以只存 (page_no, rank) 这一对，不存一个合成的全局序号。
    # keyword 进主键：同一批次里一个关键词下同一个 ASIN 只留一行（翻页去重）。
    # 长度由 common/core/searchurl.MAX_KEYWORD_LEN(200) 在写入前截断保证 ——
    # PG 的 B-tree 行宽上限 ~2704 字节，不截断的话一条超长关键词能顶爆索引。
    f"""
    CREATE TABLE IF NOT EXISTS search_discoveries (
        batch_id      bigint NOT NULL,
        keyword       text COLLATE "C" NOT NULL,
        asin          text COLLATE "C" NOT NULL,
        list_title    text COLLATE "C",
        list_price    text COLLATE "C",
        list_image    text COLLATE "C",
        page_no       integer DEFAULT 0,
        rank          integer DEFAULT 0,
        is_sponsored  integer DEFAULT 0,
        discovered_at text COLLATE "C" DEFAULT {TS_DEFAULT},
        PRIMARY KEY (batch_id, keyword, asin)
    );
    """,
]

# ------------------------------------------------------------------
# 索引：与 common/database.py:440-607 + 711-717 一一对应
# ------------------------------------------------------------------

DDL_INDEXES: List[str] = [
    "CREATE INDEX IF NOT EXISTS idx_batch_asins_asin ON batch_asins(asin)",

    "CREATE INDEX IF NOT EXISTS idx_changes_asin ON asin_changes(asin)",
    "CREATE INDEX IF NOT EXISTS idx_changes_type ON asin_changes(change_type)",
    "CREATE INDEX IF NOT EXISTS idx_changes_batch_type ON asin_changes(batch_id, change_type)",
    # change_filter 的 EXISTS 半连接（`ac.change_type = ? AND ac.asin = ?`）的支撑索引。
    # 只加索引不改写只能从 736ms 降到 678ms，两件事必须一起做：
    # 原来的 JOIN (SELECT DISTINCT asin ...) 会先把整个 change_type 桶物化去重。
    "CREATE INDEX IF NOT EXISTS idx_changes_type_asin ON asin_changes(change_type, asin)",

    "CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status)",
    "CREATE INDEX IF NOT EXISTS idx_tasks_batch ON tasks(batch_id)",
    "CREATE INDEX IF NOT EXISTS idx_tasks_status_priority ON tasks(status, priority DESC)",
    "CREATE INDEX IF NOT EXISTS idx_tasks_status_worker ON tasks(status, worker_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_tasks_status_updated ON tasks(status, updated_at)",
    # 覆盖索引：让 get_batches 的分组统计走 index-only
    "CREATE INDEX IF NOT EXISTS idx_tasks_batch_status ON tasks(batch_id, status)",
    # pull_tasks 拆分后的两条候选查询各自的有序输出都由它提供，
    # 顺带让 `SELECT MAX(priority) ... WHERE status='pending'` 走反向 index-only。
    # ⚠ NULLS FIRST 必须显式写：PG 的 ASC 默认 NULLS LAST，而 SQLite 的 ASC 是
    #   NULLS FIRST（common/database.py 的同名索引因此不写修饰符）。写错了
    #   索引顺序与 ORDER BY 对不上，规划器会退回排序 —— tasks.py:57-58 已经踩过一次。
    "CREATE INDEX IF NOT EXISTS idx_tasks_pull "
    "ON tasks(status, priority, zip_code NULLS FIRST, id)",

    "CREATE INDEX IF NOT EXISTS idx_screenshots_status ON screenshots(status)",
    "CREATE INDEX IF NOT EXISTS idx_screenshots_batch ON screenshots(batch_id)",
    # media.py:_get_done_screenshot_paths 的第二次 load() 不带 batch 过滤，
    # 而 screenshots 上原本没有任何以 asin 打头的索引（只有 UNIQUE(batch_id,asin)，
    # PG 16/17 无 B-tree skip scan —— 那是 PG 18 才有的，所以这条部分索引在 17 上
    # 依然必需）→ 否则每次 /api/results/{asin} 都吃一次全表扫。
    # 部分索引：status='done' 是该查询的固定谓词，索引只收这一部分。
    "CREATE INDEX IF NOT EXISTS idx_screenshots_asin_done "
    "ON screenshots(asin) WHERE status = 'done'",

    "CREATE INDEX IF NOT EXISTS idx_seller_disc_seller ON seller_discoveries(seller_id)",
    "CREATE INDEX IF NOT EXISTS idx_seller_disc_asin ON seller_discoveries(asin)",
    "CREATE INDEX IF NOT EXISTS idx_seller_disc_batch ON seller_discoveries(batch_id)",

    # F-010：与 seller_discoveries 的三条一一对应。batch 那条服务
    # /api/search-batches/{id}/discoveries 的默认列表，asin 那条服务
    # 「这个 ASIN 在哪些关键词下出现过」这类反查。
    "CREATE INDEX IF NOT EXISTS idx_search_disc_keyword ON search_discoveries(keyword)",
    "CREATE INDEX IF NOT EXISTS idx_search_disc_asin ON search_discoveries(asin)",
    "CREATE INDEX IF NOT EXISTS idx_search_disc_batch ON search_discoveries(batch_id)",

    "CREATE INDEX IF NOT EXISTS idx_batches_callback_pending "
    "ON batches(callback_status, callback_next_retry_at)",
]

# pg_trgm：替代 FTS5 虚表。表达式索引必须与查询里的表达式**逐字一致**，
# 否则用不上（results_read.py 必须写 ``ascii_lower(d.title) LIKE ascii_lower(?)``，
# 或者用 ``col LIKE ?`` 让 pool.translate_sql 自动改写成同一形状）。
# 实测 200k 行：建索引 6.4s，三个索引合计约 29MB（FTS5 同规模约 90MB）。
DDL_TRGM_INDEXES: List[str] = [
    "CREATE INDEX IF NOT EXISTS idx_asin_data_asin_trgm "
    "ON asin_data USING gin (public.ascii_lower(asin) public.gin_trgm_ops)",
    "CREATE INDEX IF NOT EXISTS idx_asin_data_title_trgm "
    "ON asin_data USING gin (public.ascii_lower(title) public.gin_trgm_ops)",
    "CREATE INDEX IF NOT EXISTS idx_asin_data_brand_trgm "
    "ON asin_data USING gin (public.ascii_lower(brand) public.gin_trgm_ops)",
]

# 一次性 backfill，逐字移植自 common/database.py:722-743。
# 新库上匹配 0 行（等于 no-op），但升级路径要靠它。
# 语法完全可移植；tasks.batch_id / screenshots.batch_id 都是 NOT NULL，
# 所以 ``id NOT IN (subquery)`` 不会撞上 NULL 全空的坑。
BACKFILL_LEGACY_BATCHES = """
UPDATE batches
   SET status='completed',
       completed_at=COALESCE(updated_at, created_at),
       callback_status='disabled'
 WHERE COALESCE(status,'running')='running'
   AND callback_status IS NULL
   AND id NOT IN (
     SELECT DISTINCT batch_id FROM tasks
      WHERE status NOT IN ('done','failed')
   )
   AND id NOT IN (
     SELECT DISTINCT batch_id FROM screenshots
      WHERE status NOT IN ('done','failed')
   )
"""

# ------------------------------------------------------------------
#: 建表之后跑的幂等 ALTER。**只给已存在的表补新列用**，新库上是 no-op
#: （列已经在 CREATE TABLE 里）。每一条都必须带 IF NOT EXISTS 且可反复执行。
#: ⚠ 新列一律 `ADD COLUMN`（追加到末尾），绝不改动既有列的顺序或类型 ——
#: 列序是 API 契约（`SELECT d.*` 无 response_model）。
DDL_ALTERS: List[str] = [
    'ALTER TABLE asin_data ADD COLUMN IF NOT EXISTS subtitle text COLLATE "C"',
]

# 期望列序：verify_schema() 用它做硬闸门。
# 来自 SQLite 新库（CREATE TABLE 的列 + ALTER 追加的列）的实际物理顺序。
# ``SELECT *`` / ``SELECT d.*`` 没有 response_model 过滤，改这里 = 改 API。
# ------------------------------------------------------------------
EXPECTED_COLUMNS: Dict[str, List[str]] = {
    "batches": [
        "id", "name", "needs_screenshot", "is_auto", "expand_variants", "status",
        "completed_at", "external_id", "callback_url", "callback_status",
        "callback_attempts", "callback_next_retry_at", "callback_last_error",
        "callback_sent_at", "created_at", "updated_at", "batch_type", "discover_mode",
    ],
    "batch_asins": ["batch_id", "asin", "is_new"],
    "asin_data": [
        "id", "asin", "title", "brand", "product_type", "manufacturer",
        "model_number", "part_number", "country_of_origin", "is_customized",
        "best_sellers_rank", "original_price", "current_price", "buybox_price",
        "buybox_shipping", "is_fba", "stock_count", "stock_status", "delivery_date",
        "delivery_time", "image_urls", "bullet_points", "long_description",
        "upc_list", "ean_list", "parent_asin", "variation_asins",
        "variant_attributes", "root_category_id", "category_ids", "category_tree",
        "first_available_date", "package_dimensions", "package_weight",
        "item_dimensions", "item_weight", "product_url", "site", "zip_code",
        "crawl_time", "screenshot_path", "content_hash", "title_bullets_hash",
        "baseline_price", "baseline_buybox_price", "baseline_stock_count",
        "baseline_stock_status", "baseline_title_bullets_hash",
        "baseline_updated_at", "rating", "review_count", "seller_id", "seller_name",
        "created_at", "updated_at",
        # 2026-08 追加，见 DDL 里的说明：新列只能落在末尾。
        "subtitle",
    ],
    "asin_changes": [
        "id", "asin", "batch_id", "change_type", "change_detail",
        "prev_value", "new_value", "created_at",
    ],
    "tasks": [
        "id", "batch_id", "asin", "zip_code", "status", "priority",
        "needs_screenshot", "worker_id", "lease_epoch", "retry_count",
        "auto_retry_count", "error_type", "error_detail", "created_at",
        "updated_at", "task_type", "task_meta",
    ],
    "screenshots": [
        "id", "asin", "batch_id", "status", "retry_count", "error_detail",
        "file_path", "created_at", "updated_at",
    ],
    "seller_discoveries": [
        "batch_id", "seller_id", "asin", "list_title", "list_price",
        "list_image", "discovered_at",
    ],
    "search_discoveries": [
        "batch_id", "keyword", "asin", "list_title", "list_price",
        "list_image", "page_no", "rank", "is_sponsored", "discovered_at",
    ],
}

# 带 identity 序列的表（DELETE /api/database 要把它们重启回 1）
IDENTITY_TABLES = ["batches", "asin_data", "asin_changes", "tasks", "screenshots"]

# SQLite 版 `DELETE /api/database` 清空的 6 张表。
# ⚠ 不含 seller_discoveries —— SQLite 版就不删它，保持等价。
CLEARED_TABLES = ["asin_changes", "asin_data", "batch_asins",
                  "tasks", "screenshots", "batches"]


# ==================================================================
# 事件流（Phase 2）—— schema ``scraper``，与上面的遗留表**完全分开**
# ==================================================================
#
# 为什么单开一个 schema 而不是塞进 public：
#   * ``verify_schema()`` / ``EXPECTED_COLUMNS`` 比对的是
#     ``table_schema='public'``，它存在的理由是「``SELECT d.*`` 没有
#     response_model，多一列少一列都会改 erpAPI 看到的响应」。事件流的表放在
#     ``scraper`` 下，对那道闸门天然不可见，也**必须**保持不可见。
#   * ``pool.connect()`` 把连接的 search_path 钉死成 ``public``
#     （pool.py:849/855），所以**每一处引用都必须 schema 限定**：DDL、写钩子、
#     relay，一处都不能漏。不要去改 search_path——trigram / ascii_lower
#     那一套全都假设 public。
#
# 与 `.agent/pg_migration_plan.md` §2.1 的两处**实测修正**（见 §3.1/§3.2）：
#   1. 计划里的 ``CREATE UNIQUE INDEX ON scraper.scrape_events (source_id)``
#      直接报错（**声明式分区自 PG 11 起的固有规则**，不是某个版本的限制；
#      PG 17 未放宽，实测 17.10 上仍然拒绝，tests/pgdb/test_relay.py 有反向断言）：
#        FeatureNotSupportedError: unique constraint on partitioned table must
#        include all partitioning columns
#      改成**逐分区**建唯一索引（见 EVENT_PARTITION_SOURCE_ID_INDEX_SQL）。
#      代价：跨分区的重复 source_id 抓不到。可以接受——relay 的
#      DELETE...RETURNING → INSERT 是同一个事务，同一条 outbox 行不可能被
#      relay 两次；这道索引防的是「第二个 relay 实例」，而那由
#      pg_try_advisory_lock 挡住，且真发生时也落在同一个 2000 万行窗口里。
#      **不要**为此再加一张全局去重表——那正好把设计去掉的
#      「不分区、不可裁剪、单点热行」结构又请回来。
#   2. 因此 relay 的 INSERT 只能用**无目标**的 ``ON CONFLICT DO NOTHING``；
#      ``ON CONFLICT (source_id)`` 推断不出约束，直接 raise
#      （InvalidColumnReferenceError）。
#
# **没有 DEFAULT 分区**，这是刻意的。实测溢出行为：
#     CheckViolationError: no partition of relation "scrape_events" found for row
#     DETAIL: Partition key of the failing row contains (seq) = (40000001)
# 它会让 relay 事务整体回滚 → DELETE 一起回滚 → 认领的行**全部留在 outbox**。
# 零丢失、很吵、会停摆。DEFAULT 分区则会把行照单全收，然后**永久**挡住给那个
# 区间建正确分区。宁可要那次吵闹的停摆。

EVENT_SCHEMA = "scraper"
EVENT_OUTBOX_TABLE = "scraper.scrape_outbox"
EVENT_DEAD_TABLE = "scraper.scrape_outbox_dead"
EVENT_EVENTS_TABLE = "scraper.scrape_events"
EVENT_SYNC_META_TABLE = "scraper.sync_meta"
EVENT_PARTITION_PREFIX = "scrape_events_p"

#: 每个分区覆盖的 seq 跨度。计划 §2.1：2000 万行一个分区
#: （10 万/天 ≈ 200 天，几十万/天 ≈ 40 天）。
#: 环境变量只为测试留口子——生产别动它：改小之后老分区的边界不会跟着变，
#: 新分区从「当前最高上界」往后接，所以改动是安全的、但没有意义。
EVENT_PARTITION_SPAN = int(os.environ.get("PG_EVENT_PARTITION_SPAN", "20000000"))

#: 永远保持至少这么多个「未来分区」（下界 > 当前 last_value）。计划 §2.1。
EVENT_FUTURE_PARTITIONS = int(os.environ.get("PG_EVENT_FUTURE_PARTITIONS", "2"))

#: 契约版本。写进 sync_meta，Phase 3 的 /api/v1/sync/status 要回它。
EVENT_CONTRACT_VERSION = "1"

#: outcome 封闭集（计划 §2.1 的注释 + 设计规格 §2.2）。
#: 故意**不**做成 CHECK 约束：一个越界值就会让 relay 事务永久回滚、整条流停摆，
#: 而 relay 侧已经在 Python 里归一化过了（未知值 -> parse_failed 并计数）。
EVENT_OUTCOMES = ("ok", "not_found", "blocked", "parse_failed", "stale")

#: marketplace 封闭集。计划 §2.3：**绝不**透传 parser 的 ``site``（那是 "US"）。
EVENT_MARKETPLACES = ("amazon.com",)
EVENT_DEFAULT_MARKETPLACE = "amazon.com"

# ==========================================================================
# Phase 4：采集质量信号的值域
# ==========================================================================
# 列本身在 Phase 2 的 DDL 里就已经建好了（zip_observed / zip_verify /
# completeness / parse_engine，见下方建表语句），Phase 4 补的是**值域**——
# 在此之前 relay 往这四列写的是固定占位值（relay.py 里四个 `# Phase 4` 注释）。
#
# 与 EVENT_OUTCOMES 同一条口径：**一个 CHECK 约束都不加**。
# 越界值撞上 CHECK 会让 relay 事务永久回滚 ⇒ 整条流停摆，而它本来只是
# 一条记录的某个信号脏了。归一化全部在 relay 的 Python 里做，并各带一个计数器
# （`zip_verify_coerced` / `completeness_coerced` / `parse_engine_coerced`），
# 停摆换成「计数器 + 一条 WARNING」。
#
# 还有第二个理由：这四列是 Phase 2 就建出来的，生产库里**已经存在**。
# `CREATE TABLE IF NOT EXISTS` 对已存在的表是 no-op，所以任何写在 DDL 里的新
# CHECK 只会出现在**全新库**上 —— 老库与新库的失败面从此不同，那比没有约束更糟。

#: ``zip_verify`` 封闭集（契约 §6.1 / 计划 §2.1）。worker 侧的同一份定义在
#: worker/parser.py 的 ZIP_VERIFY_* 与 worker/engine.py 的 ZIP_VERIFY_DOMAIN；
#: 三处不许漂，由 tests/pgdb/test_phase4_fields.py 的跨模块对表用例看守。
EVENT_ZIP_VERIFY_VALUES = ("confirmed", "assumed", "mismatch", "unverified")

#: 拿不准时写哪个。**永远是最弱的那个**：一个错的 confirmed 比一个诚实的
#: unverified 更糟（消费侧拿 zip_verify 决定这条价格算不算数）。
EVENT_ZIP_VERIFY_DEFAULT = "unverified"

#: ``parse_engine`` 值域（P4-9）。集外值一律写 NULL —— 契约 §6.3 已经写明
#: 「可能为 null」，猜一个引擎名等于伪造溯源信息。
EVENT_PARSE_ENGINES = ("selectolax", "lxml")

#: ``completeness`` 位图（契约 §6.4，位定义已对外公布，**不许改**）。
#:
#: P4.5：**数值不再定义在这里**，唯一真源是 ``common/core/completeness.py``
#: （worker/parser.py 的 ``COMPLETENESS_*`` 与 server/api/sync.py 的
#: ``COMPLETENESS_MEASURED_BIT`` / ``COMPLETENESS_REQUIRED_MASK`` 同源）。
#: ``EVENT_`` 前缀的别名**一个不改**：common/pgdb/relay.py:134-135 与
#: tests/pgdb/test_phase4_fields.py 都按这些名字 import，那层不用动一个字节。
#: 真源模块零依赖（不 import 任何东西），所以这条 pgdb -> core 的边不会
#: 把任何驱动拖进来，也**不会**产生反向的 core -> pgdb 依赖
#: —— 后者正是「位常量不能放在本文件」的原因（worker 也要用它，见 R4）。
from common.core.completeness import (  # noqa: E402  —— 位常量的唯一真源
    BREADCRUMB as EVENT_COMPLETENESS_BREADCRUMB,   # bit0 面包屑区块存在
    DETAIL as EVENT_COMPLETENESS_DETAIL,           # bit1 详情表存在
    IMAGE as EVENT_COMPLETENESS_IMAGE,             # bit2 主图集存在
    MEASURED as EVENT_COMPLETENESS_MEASURED,       # bit3 这次采集真的测量过上面三项
    MAX as EVENT_COMPLETENESS_MAX,
)
#: 0 = **未测量**，不是「三项都缺」。契约 §6.4 用整段写明了这个区别。
#: 它**不是**一个位，是「位图缺席」这件事本身，所以刻意留在本文件、
#: 没有搬进 common/core/completeness.py 的位常量清单。
EVENT_COMPLETENESS_UNMEASURED = 0

#: worker 在提交体里放的 `_` 前缀采集元数据键（worker/engine.py 的 META_*）。
#: `_` 开头的键**永远不会落进 asin_data**（写入侧只遍历 ASIN_DATA_FIELDS），
#: 它们唯一的去处就是事件流：payload 原样收下，relay 按下面这张表绑到同名列。
EVENT_META_OUTCOME = "_outcome"
EVENT_META_ZIP_REQUESTED = "_zip_requested"
EVENT_META_ZIP_OBSERVED = "_zip_observed"
EVENT_META_ZIP_VERIFY = "_zip_verify"
EVENT_META_COMPLETENESS = "_completeness"
EVENT_META_PARSE_ENGINE = "_parse_engine"

#: worker **只**判定这两个 outcome。blocked / parse_failed / stale 全是服务端的
#: 判定（租约门 / _is_parse_failure / outcome_for_error_type），一个 worker 声称
#: 自己 stale 是没有意义的 —— 它不知道自己的租约还在不在。
EVENT_WORKER_OUTCOMES = ("ok", "not_found")

EVENT_STREAM_DDL: List[str] = [
    "CREATE SCHEMA IF NOT EXISTS scraper",

    # ---------------- outbox：写侧入口，全并发，短命 ----------------
    # 常驻行数 ≈ 一秒的产出量，不分区、不加索引（PK 够了）。
    # enqueued_at 用 now()（= 事务开始时刻）而不是 clock_timestamp()：
    # 它就是 scrape_events.recorded_at，「一次 accept_results_batch 共享一个
    # 时间戳」是对的——那一批确实是在同一个提交里被记录下来的。
    """
    CREATE TABLE IF NOT EXISTS scraper.scrape_outbox (
        id          bigserial   PRIMARY KEY,
        enqueued_at timestamptz NOT NULL DEFAULT now(),
        body        jsonb       NOT NULL
    )
    """,

    # ---------------- 死信：relay 反复插不进去的毒丸 ----------------
    # 存在的理由：没有它，一条 body 畸形到连 NOT NULL / CHECK 都过不去的行
    # 会永远排在 ``ORDER BY id`` 的队头，让**整条事件流**永久停摆（每 tick
    # 认领它、失败、回滚，循环往复）。有了它，那种情况降级成「一行被隔离 +
    # 一条 ERROR 日志 + 一个计数器」，人可以事后捞出来重放。
    # 绝不静默丢弃：行原封不动搬过来，连 id 和 enqueued_at 都留着。
    """
    CREATE TABLE IF NOT EXISTS scraper.scrape_outbox_dead (
        id             bigint      PRIMARY KEY,
        enqueued_at    timestamptz NOT NULL,
        quarantined_at timestamptz NOT NULL DEFAULT now(),
        failure        text COLLATE "C" NOT NULL,
        body           jsonb       NOT NULL
    )
    """,

    # ---------------- 事件流：只追加，唯一写入者是 relay ----------------
    # 逐列照抄计划 §2.1，只补了 D-10 的 COLLATE "C"（字节序，扛得住
    # 「恢复进另一台 collation 不同的库」）。
    """
    CREATE TABLE IF NOT EXISTS scraper.scrape_events (
        seq           bigserial   NOT NULL,
        source_id     text COLLATE "C" NOT NULL,
        gen           text COLLATE "C" NOT NULL,
        asin          text COLLATE "C" NOT NULL,

        marketplace   text COLLATE "C" NOT NULL
                      CHECK (marketplace IN ('amazon.com')),
        zip_requested text COLLATE "C" NOT NULL,
        zip_observed  text COLLATE "C",
        zip_verify    text COLLATE "C" NOT NULL,

        collected_at  timestamptz NOT NULL,
        recorded_at   timestamptz NOT NULL,

        outcome       text COLLATE "C" NOT NULL,
        completeness  int         NOT NULL DEFAULT 0,
        error_type    text COLLATE "C",
        error_detail  text COLLATE "C",
        batch_id      bigint,
        task_id       bigint,
        worker_id     text COLLATE "C",
        attempt       int         NOT NULL DEFAULT 0,
        parse_engine  text COLLATE "C",

        review_hash   text COLLATE "C",
        slow_hash     text COLLATE "C",
        hash_ver      int         NOT NULL DEFAULT 1,

        payload       jsonb       NOT NULL,
        PRIMARY KEY (seq)
    ) PARTITION BY RANGE (seq)
    """,

    # ---------------- 同步元数据 ----------------
    # 键：contract_version / gen / instance_id / max_seq_ever / ack_seq / ...
    """
    CREATE TABLE IF NOT EXISTS scraper.sync_meta (
        k text COLLATE "C" PRIMARY KEY,
        v text COLLATE "C" NOT NULL
    )
    """,
]

#: 父表级索引（会自动传播到每个分区）。**在 p0 建好之后再建**，
#: 这样 p0 也会拿到它。/counts 按时间分桶要用。
EVENT_PARENT_INDEX_SQL = (
    "CREATE INDEX IF NOT EXISTS scrape_events_recorded_at_idx "
    "ON scraper.scrape_events (recorded_at)"
)

#: 按批次读事件流要用（`GET /api/export/batch/{batch_name}/records`）。
#: 复合 (batch_id, seq) 而不是单列 batch_id：那个端点的分页谓词是
#: `batch_id = $1 AND seq > $2 ORDER BY seq`，复合索引让它直接吃有序输出，
#: 不必把一个批次的全部事件取出来再排。
#:
#: ⚠ 与 recorded_at 那条同样是**父表级**索引，因此同样必须在 p0 建好之后才建
#: （父表 CREATE INDEX 只传播到**已存在**的分区，顺序反了 p0 就少这一条，
#: 而 p0 还要当后续分区的 LIKE 模板 —— 于是每一个分区都少）。
#: 调用点：relay.init_event_stream，紧跟在 EVENT_PARENT_INDEX_SQL 之后。
EVENT_BATCH_INDEX_SQL = (
    "CREATE INDEX IF NOT EXISTS scrape_events_batch_id_seq_idx "
    "ON scraper.scrape_events (batch_id, seq)"
)


def event_partition_name(index: int) -> str:
    return f"{EVENT_PARTITION_PREFIX}{index}"


def event_partition_source_id_index(index: int) -> str:
    """逐分区的 source_id 唯一索引名。

    ⚠ 这一条不能建在父表上（会以 FeatureNotSupportedError 拒绝 —— 声明式分区的
      固有规则，PG 11+ 均如此，17 未放宽；
    因为唯一约束必须包含分区键 seq）。所以每个分区自己带一条。
    """
    return f"{event_partition_name(index)}_source_id_key"


def event_create_first_partition_sql(span: int = None) -> List[str]:
    """p0：``FROM (MINVALUE) TO (span)``，外加它自己的 source_id 唯一索引。

    p0 必须用 ``PARTITION OF`` 直建（此刻还没有可 LIKE 的模板分区）。
    这只在建库时发生，那时不可能有 relay 在写，所以
    ``PARTITION OF`` 会拿的 ACCESS EXCLUSIVE 不会挡住任何人。
    后续分区一律走 create-then-ATTACH，见 event_next_partition_sql()。
    """
    span = EVENT_PARTITION_SPAN if span is None else span
    p0 = event_partition_name(0)
    return [
        f"CREATE TABLE IF NOT EXISTS scraper.{p0} "
        f"PARTITION OF scraper.scrape_events "
        f"FOR VALUES FROM (MINVALUE) TO ({span})",
        f"CREATE UNIQUE INDEX IF NOT EXISTS {event_partition_source_id_index(0)} "
        f"ON scraper.{p0} (source_id)",
    ]


def event_next_partition_sql(index: int, lo: int, hi: int) -> List[str]:
    """新分区的四步配方。实测（part_probe.py / v5/b1_probe.py）：

    * ``CREATE TABLE ... PARTITION OF`` 会对父表拿 **ACCESS EXCLUSIVE**，
      有写事务开着时**阻塞** > 3s —— 也就是会卡死 relay 自己。
      ``ATTACH PARTITION`` 只拿 SHARE UPDATE EXCLUSIVE，实测不阻塞。
      所以是 create standalone → ATTACH，不是 PARTITION OF。
    * 模板是**父表**，并且 source_id 唯一索引**显式**建一条 —— 与 p0 的配方逐字
      一致（见 event_create_first_partition_sql）。这一条是修 Phase 2 的
      BLOCKER B1 时改的，原来是 ``LIKE <上一个分区> INCLUDING ALL``：

        ``INCLUDING ALL`` 蕴含 ``INCLUDING CONSTRAINTS``，于是模板分区**自己那条
        range CHECK 被照抄进新分区**。p0 是 PARTITION OF 建的、没有 range CHECK，
        所以 p1 干净；但 p1 → p2 抄来了 ``scrape_events_p1_range``，此后每一个
        分区都带着一条与自己边界**矛盾**的 CHECK。实测（生产默认 SPAN，连库即现）：

            scrape_events_p2  scrape_events_p1_range  CHECK (seq >= 1000 AND seq < 2000)  <- 抄来的
            scrape_events_p2  scrape_events_p2_range  CHECK (seq >= 2000 AND seq < 3000)
            p2 seq=2001  FAIL CheckViolationError: ... violates check constraint "scrape_events_p1_range"

        两条互斥的 CHECK ⇒ 该分区**永远收不下任何行**，事件流在 seq=40,000,000
        处永久停摆；而且那个 CheckViolationError 的文本里没有
        ``no partition of relation``，``_is_row_fault()`` 会返回 True，
        于是完好的行被一条一条搬进死信表。

      为什么不是 ``INCLUDING ALL EXCLUDING CONSTRAINTS``（看起来只差一个词）：
      它把父表的 ``marketplace`` CHECK 也一起排除掉了，而 ATTACH 要求子表**事先
      具备**父表的每一条 CHECK，实测直接失败：

            DatatypeMismatchError: child table is missing constraint
                                   "scrape_events_marketplace_check"

      抄父表则天然只带父表有的东西（pkey、marketplace CHECK、recorded_at 索引），
      分区局部的 range CHECK 结构上不可能被继承 —— 这一类 bug 被根除，而不是被
      逐条排除。代价是父表上没有 source_id 唯一索引（声明式分区不允许：唯一约束必须
      包含分区键 seq），所以那一条显式补建。``_create_partition`` 的硬闸门会同时
      核对「有 source_id 唯一索引」与「有且只有一条自己的 range CHECK」。
    * 先手工挂上等价的 CHECK，ATTACH 时就能跳过全表校验扫描。
    """
    name = event_partition_name(index)
    return [
        f"CREATE TABLE IF NOT EXISTS scraper.{name} "
        f"(LIKE scraper.scrape_events INCLUDING ALL)",
        f"CREATE UNIQUE INDEX IF NOT EXISTS {event_partition_source_id_index(index)} "
        f"ON scraper.{name} (source_id)",
        f"ALTER TABLE scraper.{name} ADD CONSTRAINT {name}_range "
        f"CHECK (seq >= {lo} AND seq < {hi})",
        f"ALTER TABLE scraper.scrape_events ATTACH PARTITION scraper.{name} "
        f"FOR VALUES FROM ({lo}) TO ({hi})",
    ]


#: 一个分区身上挂着的、**属于别的分区**的 range CHECK。
#: 只有 B1 修复之前建出来的库才会有 —— 但那是**每一个** Phase 2 建的库
#: （p2 在 connect() 期就被建出来了），所以修 DDL 不够，还得能就地修好已有的库。
#: 名字模式是 schema 自己定的（``{分区名}_range``），不会误伤别人的约束。
EVENT_FOREIGN_RANGE_CHECKS_SQL = f"""
SELECT rel.relname AS partition, con.conname AS conname,
       pg_get_constraintdef(con.oid) AS condef
  FROM pg_constraint con
  JOIN pg_class rel     ON rel.oid = con.conrelid
  JOIN pg_namespace n   ON n.oid = rel.relnamespace
 WHERE n.nspname = '{EVENT_SCHEMA}'
   AND con.contype = 'c'
   AND rel.relname ~ '^{EVENT_PARTITION_PREFIX}[0-9]+$'
   AND con.conname ~ '^{EVENT_PARTITION_PREFIX}[0-9]+_range$'
   AND con.conname <> rel.relname || '_range'
 ORDER BY rel.relname, con.conname
"""


#: 某个分区身上属于**它自己**的 range CHECK（硬闸门用：必须恰好一条）。
EVENT_OWN_RANGE_CHECK_SQL = f"""
SELECT con.conname, pg_get_constraintdef(con.oid) AS condef
  FROM pg_constraint con
  JOIN pg_class rel     ON rel.oid = con.conrelid
  JOIN pg_namespace n   ON n.oid = rel.relnamespace
 WHERE n.nspname = '{EVENT_SCHEMA}' AND rel.relname = $1
   AND con.contype = 'c'
   AND con.conname ~ '^{EVENT_PARTITION_PREFIX}[0-9]+_range$'
"""


#: 已挂载分区的名字与范围上界。``pg_get_expr`` 产出形如
#: ``FOR VALUES FROM (MINVALUE) TO ('20000000')``，边界值会被引号包起来。
EVENT_LIST_PARTITIONS_SQL = """
SELECT c.relname AS name, pg_get_expr(c.relpartbound, c.oid) AS bound
  FROM pg_class c
  JOIN pg_inherits i ON i.inhrelid = c.oid
  JOIN pg_class p    ON p.oid = i.inhparent
  JOIN pg_namespace n ON n.oid = p.relnamespace
 WHERE n.nspname = 'scraper' AND p.relname = 'scrape_events'
 ORDER BY c.relname
"""

#: 事件表的列集/列序。不进 verify_schema()（那道闸门只看 public），
#: 由 relay.init_event_stream() 自查——列顺序在这里不是 API 契约，
#: 但「少了一列」必须立刻炸而不是等到第一次 INSERT。
EVENT_EXPECTED_COLUMNS: Dict[str, List[str]] = {
    "scrape_outbox": ["id", "enqueued_at", "body"],
    "scrape_outbox_dead": ["id", "enqueued_at", "quarantined_at", "failure", "body"],
    "scrape_events": [
        "seq", "source_id", "gen", "asin", "marketplace", "zip_requested",
        "zip_observed", "zip_verify", "collected_at", "recorded_at", "outcome",
        "completeness", "error_type", "error_detail", "batch_id", "task_id",
        "worker_id", "attempt", "parse_engine", "review_hash", "slow_hash",
        "hash_ver", "payload",
    ],
    "sync_meta": ["k", "v"],
}


class SchemaMixin:
    """DDL。只依赖 PoolMixin 提供的 ``self._db`` / ``self._pool``。"""

    async def init_tables(self):
        """建表建索引。幂等：可以对着已有库反复跑。

        每条语句独立自动提交（不裹在一个事务里）——这是刻意的：
        SQLite 版靠 isolation_level=None 让每条 DDL 单独提交，PG 里若裹成一个
        事务，任何一条失败都会让后面全部 ``InFailedSQLTransactionError``。
        """
        conn = self._write_conn
        if conn is None:
            raise RuntimeError("init_tables 需要已建立的写连接")

        # pg_trgm + ascii_lower：需要建扩展的权限。生产角色若没有，
        # 把这两步挪到独立的 bootstrap 脚本，init_tables 只管假设它已就绪。
        try:
            await conn.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        except Exception as e:  # noqa: BLE001
            logger.warning("pg_trgm 扩展创建失败（搜索会退化成顺序扫描）: %s", e)
        await conn.execute(ASCII_LOWER_FN)

        for stmt in DDL_TABLES:
            await conn.execute(stmt)

        # ---- 老库升级：CREATE TABLE IF NOT EXISTS 不会给已存在的表加列 ----
        # 这是 PG 侧**唯一**的一条 ALTER 迁移，与文件头「不移植 SQLite 那 27 条
        # ALTER 阶梯」并不矛盾：那段拒绝的是 `ALTER ... except: pass` 的**阶梯**
        # （裸 except 吞掉失败 -> 半张表悄悄建不出来）。这里是单条、带
        # `IF NOT EXISTS`、真幂等、失败会照常抛的语句。
        #
        # 少了它，生产库（表早已存在）拿不到 subtitle 列，verify_schema 当场
        # 拦下启动 —— 那反而是好结果；更坏的是有人把 strict 关掉，于是写入侧
        # 按列名 bind 时才炸。
        for stmt in DDL_ALTERS:
            await conn.execute(stmt)
        for stmt in DDL_INDEXES:
            await conn.execute(stmt)
        for stmt in DDL_TRGM_INDEXES:
            try:
                await conn.execute(stmt)
            except Exception as e:  # noqa: BLE001
                # 与 SQLite 版一致：搜索索引建不出来只告警，不挡启动
                logger.warning("trgm 索引初始化异常（不影响核心功能）: %s", e)

        try:
            tag = await conn.execute(BACKFILL_LEGACY_BATCHES)
            n = int(str(tag).rsplit(" ", 1)[-1])
            if n > 0:
                logger.info("数据库迁移: 回填 %d 个老批次为 completed", n)
        except Exception as e:  # noqa: BLE001
            logger.warning("老批次 backfill 异常: %s", e)

        # ---- 事件流（Phase 2）：scraper schema 下的四张表 + 分区 + gen ----
        #
        # ⚠ 这一处偏离设计规格 §3.2 的「不要从 init_tables() 建事件流表」，
        # 理由是被另外两条约束逼出来的，不是随手加的：
        #   * 规格 §1.4 要求把 relay 的入口名加进 tests/golden/harness.py 的
        #     _PATCHED_LOOPS —— 也就是**黄金重放时 relay 任务被 no-op 掉**。
        #   * 而写钩子（results_write.py，规格 §1.1）在 `DB_BACKEND=postgres`
        #     的黄金重放里**照样每写一条结果就 INSERT 一次 outbox**。
        # 于是「建表只发生在 relay 启动时」= 黄金 PG 重放第一次写结果就
        # `UndefinedTableError: relation "scraper.scrape_outbox" does not exist`，
        # 并且那条错误发生在写事务里，会连同整批结果一起回滚。
        # init_tables() 是我唯一够得着的 connect() 期入口（pool.py:860），
        # 所以建表挂在这里。EXPECTED_COLUMNS / verify_schema() 一个字没动，
        # scraper.* 对那道闸门仍然不可见（它比对的是 table_schema='public'）。
        #
        # hasattr 守卫：允许有人把 SchemaMixin 单独拼进一个没有事件流的
        # Database 里（tests/pgdb/test_skeleton.py 就在直接调 init_tables）。
        if hasattr(self, "init_event_stream"):
            await self.init_event_stream()

        # Phase 6：给 sync_meta 装上「ack_seq 永远不是 0」的 CHECK，并顺手自愈
        # 已经躺在库里的那种幽灵值。必须在事件流建表之后（约束长在 sync_meta 上）。
        # 装不上不挡启动：Python 侧的 read_ack_floor() 是同一条不变式的第一道防线，
        # 这一条是给「有人手工 UPDATE」准备的第二道。
        if hasattr(self, "ensure_retention_schema"):
            try:
                await self.ensure_retention_schema(conn)
            except Exception as e:  # noqa: BLE001
                logger.warning("保留期防线（sync_meta CHECK）装不上，跳过: %s", e)

    async def verify_schema(self, strict: bool = True) -> List[str]:
        """比对实际列序与 EXPECTED_COLUMNS。返回问题列表（空 = 一致）。

        存在的理由：``SELECT d.*`` 没有 response_model，任何多出来/少掉/换位的列
        都会直接改变 erpAPI 看到的响应。把"永远别给 asin_data 加列"从注释
        升级成硬闸门。
        """
        conn = self._write_conn
        problems: List[str] = []
        for table, expected in EXPECTED_COLUMNS.items():
            rows = await conn.fetch(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_schema='public' AND table_name=$1 "
                "ORDER BY ordinal_position", table)
            actual = [r["column_name"] for r in rows]
            if actual != expected:
                problems.append(
                    f"{table}: 列序/列集不符\n  期望={expected}\n  实际={actual}")
        if problems and strict:
            raise RuntimeError("PG schema 与 SQLite 基线不一致:\n" + "\n".join(problems))
        return problems

    async def reset_all(self):
        """清空全部业务表并把 identity 重置回 1（测试夹具用）。

        与 `DELETE /api/database` 的语义一致：不动 seller_discoveries 之外的
        取舍见 CLEARED_TABLES 注释。这里为了测试可重复性把它也一并清掉，
        search_discoveries（F-010，同样不在 CLEARED_TABLES 里）同理。
        """
        conn = self._write_conn
        await conn.execute(
            "TRUNCATE asin_changes, asin_data, batch_asins, tasks, "
            "screenshots, batches, seller_discoveries, search_discoveries "
            "RESTART IDENTITY")
